# Generated by Django 3.1.5 on 2021-01-31 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoreader', '0003_auto_20210130_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Person',
        ),
    ]
