# Generated by Django 3.1.5 on 2021-02-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0005_auto_20210131_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='No Description', max_length=200),
            preserve_default=False,
        ),
    ]
