# Generated by Django 3.1.5 on 2021-02-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0007_auto_20210202_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=200)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoreader.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoreader.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoreader.person')),
            ],
        ),
    ]
