# Generated by Django 3.1.5 on 2021-02-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0008_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
