# Generated by Django 3.1.5 on 2021-02-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0009_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
