# Generated by Django 3.1.5 on 2021-02-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0010_auto_20210203_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ImageField(upload_to='')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoreader.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoreader.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoreader.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoreader.person')),
            ],
        ),
    ]
