# Generated by Django 3.1.5 on 2021-02-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0012_auto_20210220_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='autoreader.person'),
            preserve_default=False,
        ),
    ]
