# Generated by Django 3.1.5 on 2021-02-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0013_enrollment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='response_teacher', to='autoreader.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_student', to='autoreader.person'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_teacher', to='autoreader.person'),
        ),
        migrations.AlterField(
            model_name='response',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_student', to='autoreader.person'),
        ),
    ]
