# Generated by Django 3.1.5 on 2021-03-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0014_auto_20210220_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
