# Generated by Django 3.1.5 on 2021-03-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0015_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='feedback',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
