# Generated by Django 3.1.5 on 2021-03-28 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoreader', '0016_auto_20210311_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.date(2021, 3, 28)),
        ),
    ]
